// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/ActionBar.vue')['default']
    ActionBarButton: typeof import('./components/ActionBarButton.vue')['default']
    Artplayer: typeof import('./components/Artplayer.vue')['default']
    Dialog: typeof import('./components/dialog/dialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FileInput: typeof import('./components/FileInput.vue')['default']
    ImgTray: typeof import('./components/ImgTray.vue')['default']
    Log: typeof import('./components/Log.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NavigationItem: typeof import('./components/NavigationItem.vue')['default']
    QrCode: typeof import('./components/qrCode/qrCode.vue')['default']
    QuickButton: typeof import('./components/QuickButton.vue')['default']
    SmovDetail: typeof import('./components/SmovDetail/SmovDetail.vue')['default']
    SmovIco: typeof import('./components/SmovIco.vue')['default']
    SmovItem: typeof import('./components/SmovItem.vue')['default']
  }
}

export { }
